### ISSUE TITLE
REST API: All tests are skipped

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-gpkg12#27] opened 2017-10-30 08:52 UTC
Used set up:
* Tested geopackage: http://www.geopackage.org/data/gdal_sample_v1.2_no_extensions.gpkg
* REST call: [TEAMENGINE_WEBAPP]/rest/suites/gpkg12/0.2-SNAPSHOT/run?iut=http://www.geopackage.org/data/gdal_sample_v1.2_no_extensions.gpkg
* Tested formats: EARL and ZIP

In both formats, EARL and ZIP, execution is successful but all tests are skipped.
Expected: Several tests are passed instead of being skipped.

**Comment by jyutzler** [comment] 2017-10-30 19:56
If I'm going to be able to help here, I need to know exactly how to reproduce the problem in a development environment. In general "all tests skipped" means there was no GeoPackage loaded. From my desk I can't tell why this might be the case because it obviously works in other settings including as a command line app and through the debugger.

**Comment by keshavnangare** [comment] 2017-10-31 11:55
Is there any other geopackage available?
So we can test with that whether same issue is occurring or not.

The teamengine webapp is also having this issue i.e. all tests are skipped.

Attached log:  [s0111.zip](https://github.com/opengeospatial/ets-gpkg12/files/1430551/s0111.zip)

**Comment by jyutzler** [comment] 2017-10-31 15:44
The ETS has been tested with at least 20 different GeoPackages including everything in https://github.com/opengeospatial/ets-gpkg12/tree/master/src/test/resources/gpkg via https://github.com/opengeospatial/ets-gpkg12/blob/master/src/test/java/org/opengis/cite/gpkg12/VerifyTestNGController.java
This test runs as part of the `mvn install` process so it must complete as expected for the build to be successful. There must be something wrong with how the Team Engine is running these tests, but I do not yet have the instructions for reproducing. Until that happens I can't really help you.

**Comment by jyutzler** [comment] 2017-10-31 18:42
BTW if you guys containerize the environment, it might make it easier for me to debug.

**Comment by dstenger** [comment] 2017-11-02 09:33
@jyutzler Yes, the other interfaces work. Just the REST API is not. So, the bug is definitively related to the interface and not to test implementation.
Regarding containerizing the environment: There is a Docker project to provide the test suite via Docker Image. Does this approach help you?
Keshav will do further investigation regarding this bug.

@keshav-nangare Please use tag 0.2 to reproduce the error. The referenced GeoPackage file definitively worked for me with Web Browser Interface but not with REST API.

**Comment by keshavnangare** [comment] 2017-11-02 13:32
@dstenger 

I am able to reproduce  this issue on my local environment and when we are executing the ets-gpkg12 with REST api its skipping all the tests and when executed through the webapp then there are some tests are passed.

I have investigated this issue and found the **`"ics"`** parameter as null in REST api context. Its working while using webapp because the `testRunArgs `are provided by CTL.

So we need to pass **`ics`** parameter in REST API URL.

The **`ics`** parameter used in `org.opengis.cite.gpkg12.CommonFixture` class to `validateClassEnabled` method and if the `ics` parameter is null then all classes are disabled and tests are skipped.

I have passed this `ics` parameter in the REST api URL then the some tests are passed.

Tested REST api URL with `ics` parameter: 

http://localhost:8080/teamengine/rest/suites/gpkg12/0.2/run?ics=Core%2CTiles%2CFeatures%2CExtensions%2CNon-linear+Geometries%2CRTree+Index%2CWebp%2CMetadata%2CSchema%2CCRS+WKT%2CTiled+Gridded+Elevation+Data&iut=http://www.geopackage.org/data/gdal_sample_v1.2_no_extensions.gpkg

**Comment by dstenger** [comment] 2017-11-03 11:18
@keshav-nangare Is there a way to enable all conformance classes as default setting?

**Comment by keshavnangare** [comment] 2017-11-10 11:32
@dstenger 

This test-suite is not having the levels of conformance classes as similar into the cat30 or kml22..

These "level"(Integer) attribute is used in the CommonFixture class, if we are not passing this ICS parameter through the REST API then the default(i.e. lower) level is executed.

In gpkg12 test-suite we can define the ICS values in the class, if we get the ICS value as null through the REST API then we can use these default value to validateClassEnabled.

There is one more way to get the ICS values from the test-run-props.xml file, by using this file we can get all the conformance class list.


Please provide your thoughts on this.

**Comment by dstenger** [comment] 2017-11-15 09:10
Can you solve this the same way as it is done in WFS 2.0 test suite?

If this is not possible, please add a comment here.

**Comment by keshavnangare** [comment] 2017-11-17 07:07
@dstenger 

As per my findings its not possible to enable conformance classes in ets-gpkg12 as similar to wfs20.

**Comment by dstenger** [comment] 2017-11-22 09:11
> In gpkg12 test-suite we can define the ICS values in the class, if we get the ICS value as null through the REST API then we can use these default value to validateClassEnabled.

This is the solution for the problem.

**Comment by keshavnangare** [comment] 2017-11-22 13:13
Fixed with this commit: 5640f979043672d8cefbd9da0bed5647128d1d0c

**Comment by dstenger** [comment] 2018-02-21 13:15
@keshav-nangare Can you please update PR #31?

**Comment by keshavnangare** [comment] 2018-02-22 07:56
Updated the PR #31 as per suggestion.

**Closed as completed** 2018-02-22 13:40 UTC
Labels: enhancement
